name: Call Repository Secret Migration Workflow

on:
  push:
  workflow_dispatch:
    inputs:
        repository:
          type: string
          description: 'Repository name'
          required: true

jobs:
  call-rep-secret:
    if: ${{ github.event_name != 'push' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout central repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GK_PAT }}
          path: ./source-repo

      - name: Call Repository Scoped Secret Migration Workflow
        run: |
          cd ${{ github.workspace }}/source-repo
          gh workflow run secret-migration-environment.yml --ref github-migration -F json-migration-spec=@${{ github.event.inputs.repository }}-env-spec.json
        env:
          GITHUB_TOKEN: ${{ secrets.GK_PAT }}