name: Migrate One or More Repository Secrets

on:
  workflow_call:
    inputs:
      json-migration-spec:
        type: string
        required: true
        description: >-
          A JSON structured specification of repositories to be migrated.
  workflow_dispatch:
    inputs:
      json-migration-spec:
        type: string
        required: true
        description: >-
          A JSON structured specification of repositories to be migrated.
  # expected json-migration-spec input should be structured as follows:
  # {
  #     "REPOSITORY_SECRET_01": {
  #         "secretname": "REPOSITORY_SECRET_01",
  #         "destinationRepositoryName": "repo-with-access-to-secret-01",
  #         "destinationRepositoryOwner": "migration-dst",
  #         "destinationPersonalAccessTokenName": "DST_ORG_SECRET_MGT"
  #     },
  #     "REPOSITORY_SECRET_02": {
  #         "secretname": "REPOSITORY_SECRET_02",
  #         "destinationRepositoryName": "repo-with-access-to-secret-02",
  #         "destinationRepositoryOwner": "migration-dst",
  #         "destinationPersonalAccessTokenName": "DST_ORG_SECRET_MGT"
  #     },
  #     "REPOSITORY_SECRET_03": {
  #         "secretname": "REPOSITORY_SECRET_03",
  #         "destinationRepositoryName": "repo-with-access-to-secret-03",
  #         "destinationRepositoryOwner": "migration-dst",
  #         "destinationPersonalAccessTokenName": "DST_ORG_SECRET_MGT"
  #     }
  # }

jobs:
  migrate-repository-secret:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        secretname: ${{ fromJSON(inputs.json-migration-spec).*.secretname }} # e.g. [ "p", "q", ...]
      max-parallel: 1
    steps:
      - name: Save repository secret
        uses: gh-gei-bells/github-secret/save-to-repository@main
        with:
          secret-name: ${{ matrix.secretname }} # e.g. "p"
          secret-value: ${{ secrets[matrix.secretname] }}
          destination-repository-name: ${{ fromJSON(inputs.json-migration-spec)[matrix.secretname].destinationRepositoryName }} # e.g. "repo-01"
          destination-repository-owner: ${{ fromJSON(inputs.json-migration-spec)[matrix.secretname].destinationRepositoryOwner }} # e.g. "targetorganization-a"
          destination-github-token: ${{ secrets[fromJSON(inputs.json-migration-spec)[matrix.secretname].destinationPersonalAccessTokenName] }} # e.g. secret["the_pat_a"]